apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  labels:
    app: greeting-service
    service: greeting-service
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: greeting-service
