---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-service-v1
  labels:
    app: greeting-service
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting-service
        version: v1
    spec:
      containers:
      - name: greeting-service
        image: michellenoorali/greeting-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service-v1
  labels:
    app: greeting-service
    service: greeting-service
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: greeting-service
    version: v1
---
